/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

/**
 * Top 100 most commonly used emojis.
 *
 * For the full emoji list (~1,800 emojis), copy from the playground:
 * lexical-playground/src/utils/emoji-list.ts
 *
 * Or source from: https://github.com/github/gemoji/blob/master/db/emoji.json
 */

import type {Emoji} from './EmojiPickerPlugin';

const emojiList: Array<Emoji> = [
  // Smileys - Happy
  {
    aliases: ['grinning'],
    category: 'Smileys & Emotion',
    description: 'grinning face',
    emoji: '😀',
    ios_version: '6.0',
    tags: ['smile', 'happy'],
    unicode_version: '6.1',
  },
  {
    aliases: ['smiley'],
    category: 'Smileys & Emotion',
    description: 'grinning face with big eyes',
    emoji: '😃',
    ios_version: '6.0',
    tags: ['happy', 'joy', 'haha'],
    unicode_version: '6.0',
  },
  {
    aliases: ['smile'],
    category: 'Smileys & Emotion',
    description: 'grinning face with smiling eyes',
    emoji: '😄',
    ios_version: '6.0',
    tags: ['happy', 'joy', 'laugh', 'pleased'],
    unicode_version: '6.0',
  },
  {
    aliases: ['grin'],
    category: 'Smileys & Emotion',
    description: 'beaming face with smiling eyes',
    emoji: '😁',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['laughing', 'satisfied'],
    category: 'Smileys & Emotion',
    description: 'grinning squinting face',
    emoji: '😆',
    ios_version: '6.0',
    tags: ['happy', 'haha'],
    unicode_version: '6.0',
  },
  {
    aliases: ['joy'],
    category: 'Smileys & Emotion',
    description: 'face with tears of joy',
    emoji: '😂',
    ios_version: '6.0',
    tags: ['tears', 'lol', 'laughing'],
    unicode_version: '6.0',
  },
  {
    aliases: ['rofl'],
    category: 'Smileys & Emotion',
    description: 'rolling on the floor laughing',
    emoji: '🤣',
    ios_version: '10.2',
    tags: ['lol', 'laughing'],
    unicode_version: '9.0',
  },
  {
    aliases: ['slightly_smiling_face'],
    category: 'Smileys & Emotion',
    description: 'slightly smiling face',
    emoji: '🙂',
    ios_version: '9.1',
    tags: [],
    unicode_version: '7.0',
  },
  {
    aliases: ['wink'],
    category: 'Smileys & Emotion',
    description: 'winking face',
    emoji: '😉',
    ios_version: '6.0',
    tags: ['flirt'],
    unicode_version: '6.0',
  },
  {
    aliases: ['blush'],
    category: 'Smileys & Emotion',
    description: 'smiling face with smiling eyes',
    emoji: '😊',
    ios_version: '6.0',
    tags: ['proud'],
    unicode_version: '6.0',
  },
  // Love & Affection
  {
    aliases: ['heart_eyes'],
    category: 'Smileys & Emotion',
    description: 'smiling face with heart-eyes',
    emoji: '😍',
    ios_version: '6.0',
    tags: ['love', 'crush'],
    unicode_version: '6.0',
  },
  {
    aliases: ['smiling_face_with_three_hearts'],
    category: 'Smileys & Emotion',
    description: 'smiling face with hearts',
    emoji: '🥰',
    ios_version: '12.1',
    tags: ['love'],
    unicode_version: '11.0',
  },
  {
    aliases: ['kissing_heart'],
    category: 'Smileys & Emotion',
    description: 'face blowing a kiss',
    emoji: '😘',
    ios_version: '6.0',
    tags: ['flirt'],
    unicode_version: '6.0',
  },
  {
    aliases: ['heart'],
    category: 'Smileys & Emotion',
    description: 'red heart',
    emoji: '❤️',
    ios_version: '6.0',
    tags: ['love'],
    unicode_version: '',
  },
  {
    aliases: ['two_hearts'],
    category: 'Smileys & Emotion',
    description: 'two hearts',
    emoji: '💕',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['sparkling_heart'],
    category: 'Smileys & Emotion',
    description: 'sparkling heart',
    emoji: '💖',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  // Thinking & Expressions
  {
    aliases: ['thinking'],
    category: 'Smileys & Emotion',
    description: 'thinking face',
    emoji: '🤔',
    ios_version: '9.1',
    tags: ['hmm'],
    unicode_version: '8.0',
  },
  {
    aliases: ['hugs'],
    category: 'Smileys & Emotion',
    description: 'hugging face',
    emoji: '🤗',
    ios_version: '9.1',
    tags: [],
    unicode_version: '8.0',
  },
  {
    aliases: ['sunglasses'],
    category: 'Smileys & Emotion',
    description: 'smiling face with sunglasses',
    emoji: '😎',
    ios_version: '6.0',
    tags: ['cool'],
    unicode_version: '6.0',
  },
  {
    aliases: ['roll_eyes'],
    category: 'Smileys & Emotion',
    description: 'face with rolling eyes',
    emoji: '🙄',
    ios_version: '9.1',
    tags: [],
    unicode_version: '8.0',
  },
  {
    aliases: ['smirk'],
    category: 'Smileys & Emotion',
    description: 'smirking face',
    emoji: '😏',
    ios_version: '6.0',
    tags: ['smug'],
    unicode_version: '6.0',
  },
  // Sad & Negative
  {
    aliases: ['cry'],
    category: 'Smileys & Emotion',
    description: 'crying face',
    emoji: '😢',
    ios_version: '6.0',
    tags: ['sad', 'tear'],
    unicode_version: '6.0',
  },
  {
    aliases: ['sob'],
    category: 'Smileys & Emotion',
    description: 'loudly crying face',
    emoji: '😭',
    ios_version: '6.0',
    tags: ['sad', 'cry', 'bawling'],
    unicode_version: '6.0',
  },
  {
    aliases: ['pensive'],
    category: 'Smileys & Emotion',
    description: 'pensive face',
    emoji: '😔',
    ios_version: '6.0',
    tags: ['sad'],
    unicode_version: '6.0',
  },
  {
    aliases: ['disappointed'],
    category: 'Smileys & Emotion',
    description: 'disappointed face',
    emoji: '😞',
    ios_version: '6.0',
    tags: ['sad'],
    unicode_version: '6.0',
  },
  {
    aliases: ['slightly_frowning_face'],
    category: 'Smileys & Emotion',
    description: 'slightly frowning face',
    emoji: '🙁',
    ios_version: '9.1',
    tags: [],
    unicode_version: '7.0',
  },
  {
    aliases: ['confused'],
    category: 'Smileys & Emotion',
    description: 'confused face',
    emoji: '😕',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.1',
  },
  // Surprise & Shock
  {
    aliases: ['open_mouth'],
    category: 'Smileys & Emotion',
    description: 'face with open mouth',
    emoji: '😮',
    ios_version: '6.0',
    tags: ['surprise', 'impressed', 'wow'],
    unicode_version: '6.1',
  },
  {
    aliases: ['astonished'],
    category: 'Smileys & Emotion',
    description: 'astonished face',
    emoji: '😲',
    ios_version: '6.0',
    tags: ['amazed', 'gasp'],
    unicode_version: '6.0',
  },
  {
    aliases: ['scream'],
    category: 'Smileys & Emotion',
    description: 'face screaming in fear',
    emoji: '😱',
    ios_version: '6.0',
    tags: ['horror', 'shocked'],
    unicode_version: '6.0',
  },
  {
    aliases: ['exploding_head'],
    category: 'Smileys & Emotion',
    description: 'exploding head',
    emoji: '🤯',
    ios_version: '12.1',
    tags: ['mind', 'blown'],
    unicode_version: '11.0',
  },
  // Anger & Frustration
  {
    aliases: ['angry'],
    category: 'Smileys & Emotion',
    description: 'angry face',
    emoji: '😠',
    ios_version: '6.0',
    tags: ['mad', 'annoyed'],
    unicode_version: '6.0',
  },
  {
    aliases: ['rage', 'pout'],
    category: 'Smileys & Emotion',
    description: 'pouting face',
    emoji: '😡',
    ios_version: '6.0',
    tags: ['angry'],
    unicode_version: '6.0',
  },
  {
    aliases: ['cursing_face'],
    category: 'Smileys & Emotion',
    description: 'face with symbols on mouth',
    emoji: '🤬',
    ios_version: '12.1',
    tags: ['angry', 'swearing'],
    unicode_version: '11.0',
  },
  // Sick & Tired
  {
    aliases: ['sleeping'],
    category: 'Smileys & Emotion',
    description: 'sleeping face',
    emoji: '😴',
    ios_version: '6.0',
    tags: ['zzz'],
    unicode_version: '6.1',
  },
  {
    aliases: ['mask'],
    category: 'Smileys & Emotion',
    description: 'face with medical mask',
    emoji: '😷',
    ios_version: '6.0',
    tags: ['sick', 'ill'],
    unicode_version: '6.0',
  },
  {
    aliases: ['face_with_thermometer'],
    category: 'Smileys & Emotion',
    description: 'face with thermometer',
    emoji: '🤒',
    ios_version: '9.1',
    tags: ['sick'],
    unicode_version: '8.0',
  },
  // Fun & Silly
  {
    aliases: ['stuck_out_tongue_winking_eye'],
    category: 'Smileys & Emotion',
    description: 'winking face with tongue',
    emoji: '😜',
    ios_version: '6.0',
    tags: ['prank', 'silly'],
    unicode_version: '6.0',
  },
  {
    aliases: ['stuck_out_tongue'],
    category: 'Smileys & Emotion',
    description: 'face with tongue',
    emoji: '😛',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.1',
  },
  {
    aliases: ['zany_face'],
    category: 'Smileys & Emotion',
    description: 'zany face',
    emoji: '🤪',
    ios_version: '12.1',
    tags: ['goofy', 'wacky'],
    unicode_version: '11.0',
  },
  {
    aliases: ['partying_face'],
    category: 'Smileys & Emotion',
    description: 'partying face',
    emoji: '🥳',
    ios_version: '12.1',
    tags: ['celebration', 'birthday'],
    unicode_version: '11.0',
  },
  // Gestures
  {
    aliases: ['+1', 'thumbsup'],
    category: 'People & Body',
    description: 'thumbs up',
    emoji: '👍',
    ios_version: '6.0',
    tags: ['approve', 'ok'],
    unicode_version: '6.0',
  },
  {
    aliases: ['-1', 'thumbsdown'],
    category: 'People & Body',
    description: 'thumbs down',
    emoji: '👎',
    ios_version: '6.0',
    tags: ['disapprove', 'bury'],
    unicode_version: '6.0',
  },
  {
    aliases: ['clap'],
    category: 'People & Body',
    description: 'clapping hands',
    emoji: '👏',
    ios_version: '6.0',
    tags: ['praise', 'applause'],
    unicode_version: '6.0',
  },
  {
    aliases: ['raised_hands'],
    category: 'People & Body',
    description: 'raising hands',
    emoji: '🙌',
    ios_version: '6.0',
    tags: ['hooray'],
    unicode_version: '6.0',
  },
  {
    aliases: ['pray'],
    category: 'People & Body',
    description: 'folded hands',
    emoji: '🙏',
    ios_version: '6.0',
    tags: ['please', 'hope', 'wish'],
    unicode_version: '6.0',
  },
  {
    aliases: ['wave'],
    category: 'People & Body',
    description: 'waving hand',
    emoji: '👋',
    ios_version: '6.0',
    tags: ['goodbye'],
    unicode_version: '6.0',
  },
  {
    aliases: ['v'],
    category: 'People & Body',
    description: 'victory hand',
    emoji: '✌️',
    ios_version: '6.0',
    tags: ['victory', 'peace'],
    unicode_version: '',
  },
  {
    aliases: ['handshake'],
    category: 'People & Body',
    description: 'handshake',
    emoji: '🤝',
    ios_version: '10.2',
    tags: ['deal'],
    unicode_version: '9.0',
  },
  {
    aliases: ['muscle'],
    category: 'People & Body',
    description: 'flexed biceps',
    emoji: '💪',
    ios_version: '6.0',
    tags: ['flex', 'bicep', 'strong', 'workout'],
    unicode_version: '6.0',
  },
  {
    aliases: ['crossed_fingers'],
    category: 'People & Body',
    description: 'crossed fingers',
    emoji: '🤞',
    ios_version: '10.2',
    tags: ['luck', 'hopeful'],
    unicode_version: '9.0',
  },
  {
    aliases: ['eyes'],
    category: 'People & Body',
    description: 'eyes',
    emoji: '👀',
    ios_version: '6.0',
    tags: ['look', 'see', 'watch'],
    unicode_version: '6.0',
  },
  {
    aliases: ['ok_hand'],
    category: 'People & Body',
    description: 'OK hand',
    emoji: '👌',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['hand', 'raised_hand'],
    category: 'People & Body',
    description: 'raised hand',
    emoji: '✋',
    ios_version: '6.0',
    tags: ['highfive', 'stop'],
    unicode_version: '6.0',
  },
  {
    aliases: ['raised_hand_with_fingers_splayed'],
    category: 'People & Body',
    description: 'hand with fingers splayed',
    emoji: '🖐️',
    ios_version: '9.1',
    tags: [],
    unicode_version: '7.0',
  },
  {
    aliases: ['point_up'],
    category: 'People & Body',
    description: 'index pointing up',
    emoji: '☝️',
    ios_version: '6.0',
    tags: [],
    unicode_version: '',
  },
  {
    aliases: ['point_right'],
    category: 'People & Body',
    description: 'backhand index pointing right',
    emoji: '👉',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  // Objects & Symbols
  {
    aliases: ['fire'],
    category: 'Travel & Places',
    description: 'fire',
    emoji: '🔥',
    ios_version: '6.0',
    tags: ['hot', 'burn'],
    unicode_version: '6.0',
  },
  {
    aliases: ['star'],
    category: 'Travel & Places',
    description: 'star',
    emoji: '⭐',
    ios_version: '6.0',
    tags: [],
    unicode_version: '5.1',
  },
  {
    aliases: ['star2'],
    category: 'Travel & Places',
    description: 'glowing star',
    emoji: '🌟',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['sparkles'],
    category: 'Activities',
    description: 'sparkles',
    emoji: '✨',
    ios_version: '6.0',
    tags: ['shiny'],
    unicode_version: '6.0',
  },
  {
    aliases: ['100'],
    category: 'Smileys & Emotion',
    description: 'hundred points',
    emoji: '💯',
    ios_version: '6.0',
    tags: ['score', 'perfect'],
    unicode_version: '6.0',
  },
  {
    aliases: ['boom', 'collision'],
    category: 'Smileys & Emotion',
    description: 'collision',
    emoji: '💥',
    ios_version: '6.0',
    tags: ['explode'],
    unicode_version: '6.0',
  },
  {
    aliases: ['bulb'],
    category: 'Objects',
    description: 'light bulb',
    emoji: '💡',
    ios_version: '6.0',
    tags: ['idea', 'light'],
    unicode_version: '6.0',
  },
  {
    aliases: ['speech_balloon'],
    category: 'Smileys & Emotion',
    description: 'speech balloon',
    emoji: '💬',
    ios_version: '6.0',
    tags: ['comment'],
    unicode_version: '6.0',
  },
  {
    aliases: ['thought_balloon'],
    category: 'Smileys & Emotion',
    description: 'thought balloon',
    emoji: '💭',
    ios_version: '6.0',
    tags: ['thinking'],
    unicode_version: '6.0',
  },
  // Check marks & Status
  {
    aliases: ['white_check_mark'],
    category: 'Symbols',
    description: 'check mark button',
    emoji: '✅',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['x'],
    category: 'Symbols',
    description: 'cross mark',
    emoji: '❌',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['exclamation', 'heavy_exclamation_mark'],
    category: 'Symbols',
    description: 'exclamation mark',
    emoji: '❗',
    ios_version: '6.0',
    tags: ['bang'],
    unicode_version: '5.2',
  },
  {
    aliases: ['question'],
    category: 'Symbols',
    description: 'question mark',
    emoji: '❓',
    ios_version: '6.0',
    tags: ['confused'],
    unicode_version: '6.0',
  },
  {
    aliases: ['warning'],
    category: 'Symbols',
    description: 'warning',
    emoji: '⚠️',
    ios_version: '6.0',
    tags: ['wip'],
    unicode_version: '4.0',
  },
  // Arrows
  {
    aliases: ['arrow_right'],
    category: 'Symbols',
    description: 'right arrow',
    emoji: '➡️',
    ios_version: '6.0',
    tags: [],
    unicode_version: '',
  },
  {
    aliases: ['arrow_left'],
    category: 'Symbols',
    description: 'left arrow',
    emoji: '⬅️',
    ios_version: '6.0',
    tags: [],
    unicode_version: '4.0',
  },
  {
    aliases: ['arrow_up'],
    category: 'Symbols',
    description: 'up arrow',
    emoji: '⬆️',
    ios_version: '6.0',
    tags: [],
    unicode_version: '4.0',
  },
  {
    aliases: ['arrow_down'],
    category: 'Symbols',
    description: 'down arrow',
    emoji: '⬇️',
    ios_version: '6.0',
    tags: [],
    unicode_version: '4.0',
  },
  // Nature
  {
    aliases: ['rainbow'],
    category: 'Travel & Places',
    description: 'rainbow',
    emoji: '🌈',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['sunny'],
    category: 'Travel & Places',
    description: 'sun',
    emoji: '☀️',
    ios_version: '6.0',
    tags: ['weather'],
    unicode_version: '',
  },
  {
    aliases: ['crescent_moon'],
    category: 'Travel & Places',
    description: 'crescent moon',
    emoji: '🌙',
    ios_version: '6.0',
    tags: ['night'],
    unicode_version: '6.0',
  },
  {
    aliases: ['zap'],
    category: 'Travel & Places',
    description: 'high voltage',
    emoji: '⚡',
    ios_version: '6.0',
    tags: ['lightning', 'thunder'],
    unicode_version: '4.0',
  },
  // Food & Drink
  {
    aliases: ['pizza'],
    category: 'Food & Drink',
    description: 'pizza',
    emoji: '🍕',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['hamburger'],
    category: 'Food & Drink',
    description: 'hamburger',
    emoji: '🍔',
    ios_version: '6.0',
    tags: ['burger'],
    unicode_version: '6.0',
  },
  {
    aliases: ['birthday'],
    category: 'Food & Drink',
    description: 'birthday cake',
    emoji: '🎂',
    ios_version: '6.0',
    tags: ['party'],
    unicode_version: '6.0',
  },
  {
    aliases: ['coffee'],
    category: 'Food & Drink',
    description: 'hot beverage',
    emoji: '☕',
    ios_version: '6.0',
    tags: ['cafe', 'espresso'],
    unicode_version: '4.0',
  },
  {
    aliases: ['beer'],
    category: 'Food & Drink',
    description: 'beer mug',
    emoji: '🍺',
    ios_version: '6.0',
    tags: ['drink'],
    unicode_version: '6.0',
  },
  // Activities & Events
  {
    aliases: ['tada'],
    category: 'Activities',
    description: 'party popper',
    emoji: '🎉',
    ios_version: '6.0',
    tags: ['hooray', 'party'],
    unicode_version: '6.0',
  },
  {
    aliases: ['confetti_ball'],
    category: 'Activities',
    description: 'confetti ball',
    emoji: '🎊',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['gift'],
    category: 'Activities',
    description: 'wrapped gift',
    emoji: '🎁',
    ios_version: '6.0',
    tags: ['present', 'birthday', 'christmas'],
    unicode_version: '6.0',
  },
  {
    aliases: ['trophy'],
    category: 'Activities',
    description: 'trophy',
    emoji: '🏆',
    ios_version: '6.0',
    tags: ['award', 'contest', 'winner'],
    unicode_version: '6.0',
  },
  {
    aliases: ['musical_note'],
    category: 'Objects',
    description: 'musical note',
    emoji: '🎵',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['notes'],
    category: 'Objects',
    description: 'musical notes',
    emoji: '🎶',
    ios_version: '6.0',
    tags: ['music'],
    unicode_version: '6.0',
  },
  // Animals
  {
    aliases: ['dog'],
    category: 'Animals & Nature',
    description: 'dog face',
    emoji: '🐶',
    ios_version: '6.0',
    tags: ['pet'],
    unicode_version: '6.0',
  },
  {
    aliases: ['cat'],
    category: 'Animals & Nature',
    description: 'cat face',
    emoji: '🐱',
    ios_version: '6.0',
    tags: ['pet'],
    unicode_version: '6.0',
  },
  {
    aliases: ['unicorn'],
    category: 'Animals & Nature',
    description: 'unicorn',
    emoji: '🦄',
    ios_version: '9.1',
    tags: [],
    unicode_version: '8.0',
  },
  // Misc useful
  {
    aliases: ['pushpin'],
    category: 'Objects',
    description: 'pushpin',
    emoji: '📌',
    ios_version: '6.0',
    tags: ['location'],
    unicode_version: '6.0',
  },
  {
    aliases: ['paperclip'],
    category: 'Objects',
    description: 'paperclip',
    emoji: '📎',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['memo', 'pencil'],
    category: 'Objects',
    description: 'memo',
    emoji: '📝',
    ios_version: '6.0',
    tags: ['document', 'note'],
    unicode_version: '6.0',
  },
  {
    aliases: ['email', 'e-mail'],
    category: 'Objects',
    description: 'e-mail',
    emoji: '📧',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['link'],
    category: 'Objects',
    description: 'link',
    emoji: '🔗',
    ios_version: '6.0',
    tags: [],
    unicode_version: '6.0',
  },
  {
    aliases: ['lock'],
    category: 'Objects',
    description: 'locked',
    emoji: '🔒',
    ios_version: '6.0',
    tags: ['security', 'private'],
    unicode_version: '6.0',
  },
];

export default emojiList;
